CREATE TABLE IF NOT EXISTS Clients (
    ClientID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TitlePrefix VARCHAR(20),
    FirstName VARCHAR(100) NOT NULL,
    MiddleName VARCHAR(50),
    LastName VARCHAR(100),
    TitleSuffix VARCHAR(20),
    Citizenship1 VARCHAR(50),
    Citizenship2 VARCHAR(50),
    OnboardingDate DATE NOT NULL,
    Status VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS ClientAddresses (
    AddressID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClientID BIGINT,
    AddressType VARCHAR(50),
    AddressLine1 VARCHAR(255),
    AddressLine2 VARCHAR(255),
    City VARCHAR(100),
    Zip VARCHAR(20),
    Country VARCHAR(100),
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);

CREATE TABLE IF NOT EXISTS ClientIdentifiers (
    IdentifierID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClientID BIGINT,
    IdentifierType VARCHAR(50),
    IdentifierValue VARCHAR(100),
    IssuingAuthority VARCHAR(100),
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);

CREATE TABLE IF NOT EXISTS RelatedParties (
    RelatedPartyID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClientID BIGINT,
    RelationType VARCHAR(50), -- Legal representative, Power of Attorney, Other
    TitlePrefix VARCHAR(20),
    FirstName VARCHAR(100) NOT NULL,
    MiddleName VARCHAR(50),
    LastName VARCHAR(100),
    TitleSuffix VARCHAR(20),
    Citizenship1 VARCHAR(50),
    Citizenship2 VARCHAR(50),
    OnboardingDate DATE,
    Status VARCHAR(20),
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);

CREATE TABLE IF NOT EXISTS RelatedPartyAddresses (
    AddressID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RelatedPartyID BIGINT,
    AddressType VARCHAR(50),
    AddressLine1 VARCHAR(255),
    AddressLine2 VARCHAR(255),
    City VARCHAR(100),
    Zip VARCHAR(20),
    Country VARCHAR(100),
    FOREIGN KEY (RelatedPartyID) REFERENCES RelatedParties(RelatedPartyID)
);

CREATE TABLE IF NOT EXISTS RelatedPartyIdentifiers (
    IdentifierID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RelatedPartyID BIGINT,
    IdentifierType VARCHAR(50),
    IdentifierValue VARCHAR(100),
    IssuingAuthority VARCHAR(100),
    FOREIGN KEY (RelatedPartyID) REFERENCES RelatedParties(RelatedPartyID)
);

CREATE TABLE IF NOT EXISTS AppUsers (
    UserID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    Role VARCHAR(20) NOT NULL,
    Enabled BOOLEAN NOT NULL DEFAULT TRUE
);
