CREATE TABLE IF NOT EXISTS Clients (
    ClientID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TitlePrefix VARCHAR(20),
    FirstName VARCHAR(100) NOT NULL,
    MiddleName VARCHAR(50),
    LastName VARCHAR(100),
    TitleSuffix VARCHAR(20),
    Citizenship1 VARCHAR(50),
    Citizenship2 VARCHAR(50),
    OnboardingDate DATE NOT NULL,
    Status VARCHAR(20) NOT NULL,
    NameAtBirth VARCHAR(100),
    NickName VARCHAR(100),
    Gender VARCHAR(20),
    DateOfBirth DATE,
    Language VARCHAR(50),
    Occupation VARCHAR(100),
    CountryOfTax VARCHAR(100),
    SourceOfFundsCountry VARCHAR(100),
    FATCAStatus VARCHAR(50),
    CRSStatus VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS ClientAddresses (
    AddressID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClientID BIGINT,
    AddressType VARCHAR(50),
    AddressLine1 VARCHAR(255),
    AddressLine2 VARCHAR(255),
    City VARCHAR(100),
    Zip VARCHAR(20),
    Country VARCHAR(100),
    AddressNumber VARCHAR(50),
    AddressSupplement VARCHAR(255),
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);

CREATE TABLE IF NOT EXISTS ClientIdentifiers (
    IdentifierID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClientID BIGINT,
    IdentifierType VARCHAR(50),
    IdentifierValue VARCHAR(100),
    IssuingAuthority VARCHAR(100),
    IdentifierNumber VARCHAR(100),
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);

CREATE TABLE IF NOT EXISTS RelatedParties (
    RelatedPartyID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClientID BIGINT,
    RelationType VARCHAR(50), -- Legal representative, Power of Attorney, Other
    TitlePrefix VARCHAR(20),
    FirstName VARCHAR(100) NOT NULL,
    MiddleName VARCHAR(50),
    LastName VARCHAR(100),
    TitleSuffix VARCHAR(20),
    Citizenship1 VARCHAR(50),
    Citizenship2 VARCHAR(50),
    OnboardingDate DATE,
    Status VARCHAR(20),
    NameAtBirth VARCHAR(100),
    NickName VARCHAR(100),
    Gender VARCHAR(20),
    DateOfBirth DATE,
    Language VARCHAR(50),
    Occupation VARCHAR(100),
    CountryOfTax VARCHAR(100),
    SourceOfFundsCountry VARCHAR(100),
    FATCAStatus VARCHAR(50),
    CRSStatus VARCHAR(50),
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);

CREATE TABLE IF NOT EXISTS RelatedPartyAddresses (
    AddressID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RelatedPartyID BIGINT,
    AddressType VARCHAR(50),
    AddressLine1 VARCHAR(255),
    AddressLine2 VARCHAR(255),
    City VARCHAR(100),
    Zip VARCHAR(20),
    Country VARCHAR(100),
    AddressNumber VARCHAR(50),
    AddressSupplement VARCHAR(255),
    FOREIGN KEY (RelatedPartyID) REFERENCES RelatedParties(RelatedPartyID)
);

CREATE TABLE IF NOT EXISTS RelatedPartyIdentifiers (
    IdentifierID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RelatedPartyID BIGINT,
    IdentifierType VARCHAR(50),
    IdentifierValue VARCHAR(100),
    IssuingAuthority VARCHAR(100),
    IdentifierNumber VARCHAR(100),
    FOREIGN KEY (RelatedPartyID) REFERENCES RelatedParties(RelatedPartyID)
);

CREATE TABLE IF NOT EXISTS AppUsers (
    UserID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    Role VARCHAR(20) NOT NULL,
    Enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS MaterialChanges (
    ChangeID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ChangeDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ClientID BIGINT,
    EntityID BIGINT,
    EntityName VARCHAR(255),
    ColumnName VARCHAR(255),
    OperationType VARCHAR(50),
    OldValue TEXT,
    NewValue TEXT,
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);

CREATE TABLE IF NOT EXISTS RolePermissions (
    RoleName VARCHAR(50) NOT NULL,
    Permission VARCHAR(100) NOT NULL,
    PRIMARY KEY (RoleName, Permission)
);

CREATE TABLE IF NOT EXISTS Cases (
    CaseID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClientID BIGINT NOT NULL,
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Reason VARCHAR(255),
    AssignedTo VARCHAR(50),
    Status VARCHAR(50) NOT NULL,
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);

CREATE TABLE IF NOT EXISTS CaseComments (
    CommentID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CaseID BIGINT NOT NULL,
    UserID VARCHAR(50) NOT NULL,
    CommentText TEXT NOT NULL,
    CommentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Role VARCHAR(50),
    FOREIGN KEY (CaseID) REFERENCES Cases(CaseID)
);

CREATE TABLE IF NOT EXISTS CaseDocuments (
    DocumentID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CaseID BIGINT NOT NULL,
    DocumentName VARCHAR(255) NOT NULL,
    Category VARCHAR(100),
    MimeType VARCHAR(100),
    UploadedBy VARCHAR(50),
    Comment TEXT,
    Data BLOB,
    UploadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CaseID) REFERENCES Cases(CaseID)
);

CREATE TABLE IF NOT EXISTS Accounts (
    AccountID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClientID BIGINT NOT NULL,
    AccountNumber VARCHAR(50) NOT NULL,
    AccountStatus VARCHAR(20) NOT NULL,
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);

CREATE TABLE IF NOT EXISTS QuestionnaireSections (
    SectionID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SectionName VARCHAR(255) NOT NULL,
    DisplayOrder INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS QuestionnaireQuestions (
    QuestionID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SectionID BIGINT NOT NULL,
    QuestionText TEXT NOT NULL,
    QuestionType VARCHAR(20) NOT NULL, -- TEXT, YES_NO, MULTI_CHOICE
    IsMandatory BOOLEAN NOT NULL DEFAULT FALSE,
    Options TEXT, -- Comma-separated for MULTI_CHOICE
    DisplayOrder INT NOT NULL DEFAULT 0,
    RiskFactorKey VARCHAR(50), -- ADVERSE_MEDIA, SUSPECIOUS_ACTIVITY_REPORT, INVESTOR_VISA
    FOREIGN KEY (SectionID) REFERENCES QuestionnaireSections(SectionID)
);

CREATE TABLE IF NOT EXISTS CaseQuestionnaireResponses (
    ResponseID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CaseID BIGINT NOT NULL,
    QuestionID BIGINT NOT NULL,
    AnswerText TEXT,
    FOREIGN KEY (CaseID) REFERENCES Cases(CaseID),
    FOREIGN KEY (QuestionID) REFERENCES QuestionnaireQuestions(QuestionID),
    UNIQUE (CaseID, QuestionID)
);

CREATE TABLE IF NOT EXISTS Portfolios (
    PortfolioID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClientID BIGINT NOT NULL,
    AccountNumber VARCHAR(50),
    PortfolioText VARCHAR(255) NOT NULL,
    OnboardingDate DATE NOT NULL,
    OffboardingDate DATE,
    Status VARCHAR(20) NOT NULL,
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);



CREATE TABLE IF NOT EXISTS RiskAssessmentLogs (
    LogID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RequestJSON CLOB,
    ResponseJSON CLOB,
    Status VARCHAR(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS RiskAssessments (
    AssessmentID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LogID BIGINT,
    RecordID VARCHAR(50),
    OverallRiskScore INT,
    InitialRiskLevel VARCHAR(50),
    OverallRiskLevel VARCHAR(50),
    TypeOfLogicApplied VARCHAR(255),
    SmeRiskAssessment VARCHAR(255),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (LogID) REFERENCES RiskAssessmentLogs(LogID)
);

CREATE TABLE IF NOT EXISTS RiskAssessmentDetails (
    DetailID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AssessmentID BIGINT,
    RiskType VARCHAR(100),
    ElementName VARCHAR(100),
    ElementValue VARCHAR(255),
    RiskScore INT,
    Flag VARCHAR(50),
    LocalRuleApplied VARCHAR(10),
    FOREIGN KEY (AssessmentID) REFERENCES RiskAssessments(AssessmentID)
);

CREATE TABLE IF NOT EXISTS CaseEvents (
    EventID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CaseID BIGINT NOT NULL,
    EventType VARCHAR(50) NOT NULL, -- RISK_CHANGED, SCREENING_HIT, NEW_ONBOARDING, OTHER
    EventDescription TEXT,
    EventDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EventSource VARCHAR(50), -- CRRE, SYSTEM, USER
    FOREIGN KEY (CaseID) REFERENCES Cases(CaseID)
);

CREATE TABLE IF NOT EXISTS ScreeningLogs (
    LogID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ClientID BIGINT,
    RequestPayload CLOB,
    ResponsePayload CLOB,
    OverallStatus VARCHAR(50),
    ExternalRequestID VARCHAR(100),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);

CREATE TABLE IF NOT EXISTS ScreeningResults (
    ResultID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ScreeningLogID BIGINT,
    ContextType VARCHAR(50), -- PEP, ADM, INT, SAN
    Status VARCHAR(50), -- HIT, NO_HIT, IN_PROGRESS
    AlertStatus VARCHAR(50),
    AlertMessage TEXT,
    AlertID VARCHAR(100),
    FOREIGN KEY (ScreeningLogID) REFERENCES ScreeningLogs(LogID)
);

